require: rubocop-rspec
AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Excludes: ['lib/protocol/icmp/**/*', 'lib/version.rb']
Metrics/MethodLength:
  Max: 15
Style/InfiniteLoop:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
RSpec/ExampleLength:
  Max: 10
Style/Documentation:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
Style/Semicolon:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 2
