# frozen_string_literal: true

source 'https://rubygems.org'

gem 'anyway_config', '~> 2.0'
gem 'async-container', '~> 0.16.12'
gem 'async-io', '~> 1.34', '>= 1.34.3'
gem 'click_house', '~> 2.1', '>= 2.1.2'
gem 'connection_pool', '~> 2.4'
gem 'dry-matcher', '~> 1.0'
gem 'dry-monads', '~> 1.6'
gem 'dry-system', '~> 1.0.1'
gem 'dry-validation', '~> 1.10'
gem 'falcon', '~> 0.42.3'
gem 'hanami-api', '~> 0.3.0'
gem 'oj', '~> 3.14', '>= 3.14.2'
gem 'rack-cors', '~> 2.0', '>= 2.0.1'
gem 'redis', '~> 5.0', '>= 5.0.6'
gem 'samovar', '~> 2.1', '>= 2.1.4'

group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :development do
  gem 'rubocop'
end

group :test do
  gem 'async-rspec', '~> 1.16', '>= 1.16.1'
  gem 'database_cleaner-redis'
  gem 'rspec'
  gem 'rubocop-rspec'
  gem 'simplecov', require: false
end
